### ISSUE TITLE
Are we there yet ?

### ISSUE THREAD

**Issue by prjctimg** [prjctimg/huetiful#127]
Hey devs, its been ages. Just doing a quick sanity check 😄 to see if you're all doing well.

Missing your activity!

@H-K-R @adarshswaminath @foss2cyber @takanome-dev @arcVaishali

**Comment by prjctimg** [comment]
![Screenshot_2024-01-21-14-22-38.jpg](https://github.com/prjctimg/huetiful/assets/104896135/8783ee9f-209b-41b4-8dd0-eeed56da07e9)



The current state of our landing page. Simplicity won the battle at the end of the day. 


Thank you all for your support throughout this project 🙏

**Comment by takanome-dev** [comment]
Hey y'all, I'm doing pretty good 😃 

haven't been contributing to open source for like 4 months (😱)just been busy with work and freelance projects but will start being more active soon hopefully.

Thanks for checking in 🤗

**Comment by prjctimg** [comment]
That's great! I'm confident you're pushing through! Looking for ideas on how to monetize this project. Working on changes for v2

Will update you soon 🚀

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
