### ISSUE TITLE
Improving the UX for docs

### ISSUE THREAD

**Issue by prjctimg** [prjctimg/huetiful#69]
### Discussed in https://github.com/prjctimg/huetiful/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **prjctimg** October 24, 2023</sup>
A lot of effort needs to be put into improving the overall UX of the documentation site. 

Over the next month we'll be adding small but noticeable improvements to help make it easier to navigate the site. Contributions are greatly appreciated devs!!</div>

#### Homepage
- [x] #70

#### Reading View
- [ ] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #75

#### List View
- [x] #76

**Comment by takanome-dev** [comment]
How about listing the things (UX improvements mentioned in https://github.com/prjctimg/huetiful/discussions/62) that need to be done here and make this issue a tracking issue? 

We can then open separate issues for each task. This way it will be easier to keep track of what needs to be done and make easier the review process.

**Comment by prjctimg** [comment]
> How about listing the things (UX improvements mentioned in https://github.com/prjctimg/huetiful/discussions/62) that need to be done here and make this issue a tracking issue? 
> 
> We can then open separate issues for each task. This way it will be easier to keep track of what needs to be done and make easier the review process.

That's a brilliant idea! Feel free to handle the issue tracking as you see effecient! 

I have no prior experience in working with GitHub Issues so I'm willing to learn the best practices!

**Comment by takanome-dev** [comment]
@prjctimg, I have opened a couple of issues for the improvements. Feel free to modify them and add more details if needed.

@adarshswaminath, feel free to grab any issue(s) you feel comfortable with.

**Comment by prjctimg** [comment]
> @prjctimg, I have opened a couple of issues for the improvements. Feel free to modify them and add more details if needed.
> 
> @adarshswaminath, feel free to grab any issue(s) you feel comfortable with.

@takanome-dev 
This looks better and more manageable already.

Reviewing the new issues now 👍

**Comment by prjctimg** [comment]
Just updated the docs. The results are not so satisfying as I expected. The reading view looks okay on the mobile browser but styling seems to break on desktop browser 🤯. **slowly getting frustrated

You can preview the site [here](https://huetiful-docs.vercel.app)


There's two things I'm thinking could be causing the style inconsistencies

1. Originally the docs are generated in `.md` format and then I change the extension to `.mdx` after injecting the typedoc generated docs into the template files. Will using the plain `.md` format fix this issue?
2. Our stylesheet is removing the default Markdown styling therefore making all the elements appear similar. 

I was on Microsoft Edge when I saw this issue on the desktop browser. 


Please let me know if you notice the inconsistencies too on your side.

@adarshswaminath @takanome-dev @foss2cyber

**Comment by prjctimg** [comment]
Just updated the docs. The results are not so satisfying as I expected. The reading view looks okay on the mobile browser but styling seems to break on desktop browser 🤯. **slowly getting frustrated

You can preview the site [here](https://huetiful-docs.vercel.app)


There's two things I'm thinking could be causing the style inconsistencies

1. Originally the docs are generated in `.md` format and then I change the extension to `.mdx` after injecting the typedoc generated docs into the template files. Will using the plain `.md` format fix this issue?
2. Our stylesheet is removing the default Markdown styling therefore making all the elements appear similar. 

I was on Microsoft Edge when I saw this issue on the desktop browser. 


Please let me know if you notice the inconsistencies too on your side and have suggestions for the best way forward with least obstacles.



@adarshswaminath @takanome-dev @foss2cyber

**Comment by adarshswaminath** [comment]
I'm currently using Brave, and the desktop view is working great! However, I've noticed some areas for improvement in the mobile view. 😊

I want to apologize as I'm unable to work on any tasks right now due to my exams. Once my exams are over, I'll be able to make more contributions to the project @prjctimg

**Comment by foss2cyber** [comment]
@prjctimg I've previewd the site on both Chrome & Firefox. Looks fine on desktop, but a few glitches in the mobile view.

**Comment by prjctimg** [comment]
@adarshswaminath @foss2cyber 

Thanks for reviewing! 🚀

Can you please note down a few areas you think we should work on **immediately** ?

At the moment our goal is to make the docs easily readable so that we can improve the overall developer experience. In fact, we're hoping to release v1.7.8 on npm on Monday (at the moment we have prereleases).
We cannot add more features if we can't make developers use what we have already developed so far.

**Comment by prjctimg** [comment]
> @prjctimg I've previewd the site on both Chrome & Firefox. Looks fine on desktop, but a few glitches in the mobile view. 

Could you please share screenshots ? Maybe my Microsoft Edge is buggy

**Comment by prjctimg** [comment]
> I'm currently using Brave, and the desktop view is working great! However, I've noticed some areas for improvement in the mobile view. 😊
> 
> I want to apologize as I'm unable to work on any tasks right now due to my exams. Once my exams are over, I'll be able to make more contributions to the project @prjctimg 

No worries! We'll be sure to keep a heap of issues awaiting your resolve 😂 👍

**Comment by foss2cyber** [comment]
> > @prjctimg I've previewd the site on both Chrome & Firefox. Looks fine on desktop, but a few glitches in the mobile view.
> 
> Could you please share screenshots ? Maybe my Microsoft Edge is buggy @foss2cyber

Sorry for replying so late, mate. Sharing screenshots below:

- Desktop (Chrome):

![desktop_chrome](https://github.com/prjctimg/huetiful/assets/78159236/594fe3bc-ad24-4941-9e18-de130b528b39)

- Desktop (Firefox):

![desktop_firefox](https://github.com/prjctimg/huetiful/assets/78159236/a1243716-797b-4f7e-91d4-81d4933fcc9c)

- Mobile (Chrome):

![mobile_chrome](https://github.com/prjctimg/huetiful/assets/78159236/efe98a59-782a-4241-bdd0-9565be945c3d)

- Mobile (Firefox_screenshot 1-3):

![mobile_firefox_1](https://github.com/prjctimg/huetiful/assets/78159236/6ae1acf9-03c4-4cef-8c6e-4121ea43d6f8)

![mobile_firefox_2](https://github.com/prjctimg/huetiful/assets/78159236/c4bc182a-c2d1-42dc-9abc-47930c4e1331)

![mobile_firefox_3](https://github.com/prjctimg/huetiful/assets/78159236/237e381c-5773-4cf6-aa20-726561d943aa)

**Comment by prjctimg** [comment]
@foss2cyber Thanks for testing it out! I think it was because of my internet connection being slow so it wasn't properly loading the stylesheet. Our network says 4G but behaves like slow 3G 😂


Making a PR for releasing v1.7.8 now. 👍
