### ISSUE TITLE
Enhancement: Improve the README description. 

### ISSUE THREAD

**Issue by prjctimg** [prjctimg/huetiful#78]
The project's README is undeniably boring and too vague. 

Let's make it comprehensive and give it lots of example use cases to give our users a starting point #77

**Comment by prjctimg** [comment]
Will add examples and more badges tonight.

**Comment by Cubic-ctrl** [comment]
Yes. I too recommend you add examples of the library in use. Common use case code snippets will demonstrate the purpose of the library.

**Comment by prjctimg** [comment]
> Yes. I too recommend you add examples of the library in use. Common use case code snippets will demonstrate the purpose of the library.

 @Cubic-ctrl Working on it right now. 

Will share the new draft later this evening!

**Comment by prjctimg** [comment]
README has been updated with a more detailed approach of explaining what the project is all about.
