### ISSUE TITLE
Enhancement:Customize the CONTRIBUTING file for the issues.yml workflow

### ISSUE THREAD

**Issue by prjctimg** [prjctimg/huetiful#87]
Will customize the CONTRIBUTING file for the issues.yml workflow

Thanks! 🚀 @takanome-dev

_Originally posted by @prjctimg in https://github.com/prjctimg/huetiful/issues/85#issuecomment-1806460474_

Creating a CONTRIBUTING file to help people interested in the project get started on contributing to our efforts would greatly benefit this project. 

Any suggestions are greatly appreciated!

**Comment by takanome-dev** [comment]
A couple of guides that I found interesting:
- https://docs.opensauced.pizza/contributing/introduction-to-contributing/
- https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md
- https://github.com/takanome-dev/blog-with-astro-golang/blob/main/CONTRIBUTING.md
- we can the following link for beginners -> https://opensource.guide/how-to-contribute/ (awesome guide)

**Comment by prjctimg** [comment]
> A couple of guides that I found interesting:
> - https://docs.opensauced.pizza/contributing/introduction-to-contributing/
> - https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md
> - https://github.com/takanome-dev/blog-with-astro-golang/blob/main/CONTRIBUTING.md
> - we can the following link for beginners -> https://opensource.guide/how-to-contribute/ (awesome guide)

Awesome! Checking them out right now and will create a draft CONTRIBUTING.md

**Comment by prjctimg** [comment]
> A couple of guides that I found interesting:
> - https://docs.opensauced.pizza/contributing/introduction-to-contributing/
> - https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md
> - https://github.com/takanome-dev/blog-with-astro-golang/blob/main/CONTRIBUTING.md
> - we can the following link for beginners -> https://opensource.guide/how-to-contribute/ (awesome guide)

Awesome! Checking them out right now and will create a draft CONTRIBUTING.md

**Comment by prjctimg** [comment]
Rewrote the CONTRIBUTING file and added comprehensive steps and guidelines to help new contributors get started.

Will probably include the coding conventions in the futy
