### ISSUE TITLE
Chore: add release cycle

### ISSUE THREAD

**Issue by takanome-dev** [prjctimg/huetiful#92]
I've noticed that the project doesn't release often enough to stay afloat in terms of traffic on both GitHub and NPM. To improve our outreach, how can we maintain a development pace that allows us to release patches or updates to the library at least once a week. This observation was inspired by open-sauced which mantains a very active release cycle. 

Ideas and suggestions for workflow management are greatly welcome! 

Let's make this project active and thriving! 🚀

_Originally posted by @prjctimg in https://github.com/prjctimg/huetiful/discussions/86_

**Comment by prjctimg** [comment]
Stale issue message
